export const enum StoreName {
  GLOBALSTATE = 'GLOBALSTATE',
  MAINSTATE = 'MAINSTATE',
  USERSTATE = 'USERSTATE',
  GAMESTATE = 'GAMESTATE',
  NORMALSTATE = 'NORMALSTATE',
  HOMESTATE = 'HOMESTATE',
  DISCOUNTSTATE = 'DISCOUNTSTATE',
  ENVSTATE = 'ENVSTATE'
}