import { lang } from '@/i18n'

export const emojiUrl = 'https://imgcache.qq.com/open/qcloud/tim/assets/emoji/'
export const emojiMap = {
  [`[${lang('NO')}]`]: 'emoji_0@2x.png',
  [`[${lang('OK')}]`]: 'emoji_1@2x.png',
  [`[${lang('下雨')}]`]: 'emoji_2@2x.png',
  [`[${lang('么么哒')}]`]: 'emoji_3@2x.png',
  [`[${lang('乒乓')}]`]: 'emoji_4@2x.png',
  [`[${lang('便便')}]`]: 'emoji_5@2x.png',
  [`[${lang('信封')}]`]: 'emoji_6@2x.png',
  [`[${lang('偷笑')}]`]: 'emoji_7@2x.png',
  [`[${lang('傲慢')}]`]: 'emoji_8@2x.png',
  [`[${lang('再见')}]`]: 'emoji_9@2x.png',
  [`[${lang('冷汗')}]`]: 'emoji_10@2x.png',
  [`[${lang('凋谢')}]`]: 'emoji_11@2x.png',
  [`[${lang('刀')}]`]: 'emoji_12@2x.png',
  [`[${lang('删除')}]`]: 'emoji_13@2x.png',
  [`[${lang('勾引')}]`]: 'emoji_14@2x.png',
  [`[${lang('发呆')}]`]: 'emoji_15@2x.png',
  [`[${lang('发抖')}]`]: 'emoji_16@2x.png',
  [`[${lang('可怜')}]`]: 'emoji_17@2x.png',
  [`[${lang('可爱')}]`]: 'emoji_18@2x.png',
  [`[${lang('右哼哼')}]`]: 'emoji_19@2x.png',
  [`[${lang('右太极')}]`]: 'emoji_20@2x.png',
  [`[${lang('右车头')}]`]: 'emoji_21@2x.png',
  [`[${lang('吐')}]`]: 'emoji_22@2x.png',
  [`[${lang('吓')}]`]: 'emoji_23@2x.png',
  [`[${lang('咒骂')}]`]: 'emoji_24@2x.png',
  [`[${lang('咖啡')}]`]: 'emoji_25@2x.png',
  [`[${lang('啤酒')}]`]: 'emoji_26@2x.png',
  [`[${lang('嘘')}]`]: 'emoji_27@2x.png',
  [`[${lang('回头')}]`]: 'emoji_28@2x.png',
  [`[${lang('困')}]`]: 'emoji_29@2x.png',
  [`[${lang('坏笑')}]`]: 'emoji_30@2x.png',
  [`[${lang('多云')}]`]: 'emoji_31@2x.png',
  [`[${lang('大兵')}]`]: 'emoji_32@2x.png',
  [`[${lang('大哭')}]`]: 'emoji_33@2x.png',
  [`[${lang('太阳')}]`]: 'emoji_34@2x.png',
  [`[${lang('奋斗')}]`]: 'emoji_35@2x.png',
  [`[${lang('奶瓶')}]`]: 'emoji_36@2x.png',
  [`[${lang('委屈')}]`]: 'emoji_37@2x.png',
  [`[${lang('害羞')}]`]: 'emoji_38@2x.png',
  [`[${lang('尴尬')}]`]: 'emoji_39@2x.png',
  [`[${lang('左哼哼')}]`]: 'emoji_40@2x.png',
  [`[${lang('左太极')}]`]: 'emoji_41@2x.png',
  [`[${lang('左车头')}]`]: 'emoji_42@2x.png',
  [`[${lang('差劲')}]`]: 'emoji_43@2x.png',
  [`[${lang('弱')}]`]: 'emoji_44@2x.png',
  [`[${lang('强')}]`]: 'emoji_45@2x.png',
  [`[${lang('彩带')}]`]: 'emoji_46@2x.png',
  [`[${lang('彩球')}]`]: 'emoji_47@2x.png',
  [`[${lang('得意')}]`]: 'emoji_48@2x.png',
  [`[${lang('微笑')}]`]: 'emoji_49@2x.png',
  [`[${lang('心碎了')}]`]: 'emoji_50@2x.png',
  [`[${lang('快哭了')}]`]: 'emoji_51@2x.png',
  [`[${lang('怄火')}]`]: 'emoji_52@2x.png',
  [`[${lang('怒')}]`]: 'emoji_53@2x.png',
  [`[${lang('惊恐')}]`]: 'emoji_54@2x.png',
  [`[${lang('惊讶')}]`]: 'emoji_55@2x.png',
  [`[${lang('憨笑')}]`]: 'emoji_56@2x.png',
  [`[${lang('手枪')}]`]: 'emoji_57@2x.png',
  [`[${lang('打哈欠')}]`]: 'emoji_58@2x.png',
  [`[${lang('抓狂')}]`]: 'emoji_59@2x.png',
  [`[${lang('折磨')}]`]: 'emoji_60@2x.png',
  [`[${lang('抠鼻')}]`]: 'emoji_61@2x.png',
  [`[${lang('抱抱')}]`]: 'emoji_62@2x.png',
  [`[${lang('抱拳')}]`]: 'emoji_63@2x.png',
  [`[${lang('拳头')}]`]: 'emoji_64@2x.png',
  [`[${lang('挥手')}]`]: 'emoji_65@2x.png',
  [`[${lang('握手')}]`]: 'emoji_66@2x.png',
  [`[${lang('撇嘴')}]`]: 'emoji_67@2x.png',
  [`[${lang('擦汗')}]`]: 'emoji_68@2x.png',
  [`[${lang('敲打')}]`]: 'emoji_69@2x.png',
  [`[${lang('晕')}]`]: 'emoji_70@2x.png',
  [`[${lang('月亮')}]`]: 'emoji_71@2x.png',
  [`[${lang('棒棒糖')}]`]: 'emoji_72@2x.png',
  [`[${lang('汽车')}]`]: 'emoji_73@2x.png',
  [`[${lang('沙发')}]`]: 'emoji_74@2x.png',
  [`[${lang('流汗')}]`]: 'emoji_75@2x.png',
  [`[${lang('流泪')}]`]: 'emoji_76@2x.png',
  [`[${lang('激动')}]`]: 'emoji_77@2x.png',
  [`[${lang('灯泡')}]`]: 'emoji_78@2x.png',
  [`[${lang('炸弹')}]`]: 'emoji_79@2x.png',
  [`[${lang('熊猫')}]`]: 'emoji_80@2x.png',
  [`[${lang('爆筋')}]`]: 'emoji_81@2x.png',
  [`[${lang('爱你')}]`]: 'emoji_82@2x.png',
  [`[${lang('爱心')}]`]: 'emoji_83@2x.png',
  [`[${lang('爱情')}]`]: 'emoji_84@2x.png',
  [`[${lang('猪头')}]`]: 'emoji_85@2x.png',
  [`[${lang('猫咪')}]`]: 'emoji_86@2x.png',
  [`[${lang('献吻')}]`]: 'emoji_87@2x.png',
  [`[${lang('玫瑰')}]`]: 'emoji_88@2x.png',
  [`[${lang('瓢虫')}]`]: 'emoji_89@2x.png',
  [`[${lang('疑问')}]`]: 'emoji_90@2x.png',
  [`[${lang('白眼')}]`]: 'emoji_91@2x.png',
  [`[${lang('皮球')}]`]: 'emoji_92@2x.png',
  [`[${lang('睡觉')}]`]: 'emoji_93@2x.png',
  [`[${lang('磕头')}]`]: 'emoji_94@2x.png',
  [`[${lang('示爱')}]`]: 'emoji_95@2x.png',
  [`[${lang('礼品袋')}]`]: 'emoji_96@2x.png',
  [`[${lang('礼物')}]`]: 'emoji_97@2x.png',
  [`[${lang('篮球')}]`]: 'emoji_98@2x.png',
  [`[${lang('米饭')}]`]: 'emoji_99@2x.png',
  [`[${lang('糗大了')}]`]: 'emoji_100@2x.png',
  [`[${lang('红双喜')}]`]: 'emoji_101@2x.png',
  [`[${lang('红灯笼')}]`]: 'emoji_102@2x.png',
  [`[${lang('纸巾')}]`]: 'emoji_103@2x.png',
  [`[${lang('胜利')}]`]: 'emoji_104@2x.png',
  [`[${lang('色')}]`]: 'emoji_105@2x.png',
  [`[${lang('药')}]`]: 'emoji_106@2x.png',
  [`[${lang('菜刀')}]`]: 'emoji_107@2x.png',
  [`[${lang('蛋糕')}]`]: 'emoji_108@2x.png',
  [`[${lang('蜡烛')}]`]: 'emoji_109@2x.png',
  [`[${lang('街舞')}]`]: 'emoji_110@2x.png',
  [`[${lang('衰')}]`]: 'emoji_111@2x.png',
  [`[${lang('西瓜')}]`]: 'emoji_112@2x.png',
  [`[${lang('调皮')}]`]: 'emoji_113@2x.png',
  [`[${lang('象棋')}]`]: 'emoji_114@2x.png',
  [`[${lang('跳绳')}]`]: 'emoji_115@2x.png',
  [`[${lang('跳跳')}]`]: 'emoji_116@2x.png',
  [`[${lang('车厢')}]`]: 'emoji_117@2x.png',
  [`[${lang('转圈')}]`]: 'emoji_118@2x.png',
  [`[${lang('鄙视')}]`]: 'emoji_119@2x.png',
  [`[${lang('酷')}]`]: 'emoji_120@2x.png',
  [`[${lang('钞票')}]`]: 'emoji_121@2x.png',
  [`[${lang('钻戒')}]`]: 'emoji_122@2x.png',
  [`[${lang('闪电')}]`]: 'emoji_123@2x.png',
  [`[${lang('闭嘴')}]`]: 'emoji_124@2x.png',
  [`[${lang('闹钟')}]`]: 'emoji_125@2x.png',
  [`[${lang('阴险')}]`]: 'emoji_126@2x.png',
  [`[${lang('难过')}]`]: 'emoji_127@2x.png',
  [`[${lang('雨伞')}]`]: 'emoji_128@2x.png',
  [`[${lang('青蛙')}]`]: 'emoji_129@2x.png',
  [`[${lang('面条')}]`]: 'emoji_130@2x.png',
  [`[${lang('鞭炮')}]`]: 'emoji_131@2x.png',
  [`[${lang('风车')}]`]: 'emoji_132@2x.png',
  [`[${lang('飞吻')}]`]: 'emoji_133@2x.png',
  [`[${lang('飞机')}]`]: 'emoji_134@2x.png',
  [`[${lang('饥饿')}]`]: 'emoji_135@2x.png',
  [`[${lang('香蕉')}]`]: 'emoji_136@2x.png',
  [`[${lang('骷髅')}]`]: 'emoji_137@2x.png',
  [`[${lang('麦克风')}]`]: 'emoji_138@2x.png',
  [`[${lang('麻将')}]`]: 'emoji_139@2x.png',
  [`[${lang('鼓掌')}]`]: 'emoji_140@2x.png',
  [`[${lang('龇牙')}]`]: 'emoji_141@2x.png',
}
export const emojiName = [
  `[${lang('龇牙')}]`,
  `[${lang('调皮')}]`,
  `[${lang('流汗')}]`,
  `[${lang('偷笑')}]`,
  `[${lang('再见')}]`,
  `[${lang('敲打')}]`,
  `[${lang('擦汗')}]`,
  `[${lang('猪头')}]`,
  `[${lang('玫瑰')}]`,
  `[${lang('流泪')}]`,
  `[${lang('大哭')}]`,
  `[${lang('嘘')}]`,
  `[${lang('酷')}]`,
  `[${lang('抓狂')}]`,
  `[${lang('委屈')}]`,
  `[${lang('便便')}]`,
  `[${lang('炸弹')}]`,
  `[${lang('菜刀')}]`,
  `[${lang('可爱')}]`,
  `[${lang('色')}]`,
  `[${lang('害羞')}]`,
  `[${lang('得意')}]`,
  `[${lang('吐')}]`,
  `[${lang('微笑')}]`,
  `[${lang('怒')}]`,
  `[${lang('尴尬')}]`,
  `[${lang('惊恐')}]`,
  `[${lang('冷汗')}]`,
  `[${lang('爱心')}]`,
  `[${lang('示爱')}]`,
  `[${lang('白眼')}]`,
  `[${lang('傲慢')}]`,
  `[${lang('难过')}]`,
  `[${lang('惊讶')}]`,
  `[${lang('疑问')}]`,
  `[${lang('困')}]`,
  `[${lang('么么哒')}]`,
  `[${lang('憨笑')}]`,
  `[${lang('爱情')}]`,
  `[${lang('衰')}]`,
  `[${lang('撇嘴')}]`,
  `[${lang('阴险')}]`,
  `[${lang('奋斗')}]`,
  `[${lang('发呆')}]`,
  `[${lang('右哼哼')}]`,
  `[${lang('抱抱')}]`,
  `[${lang('坏笑')}]`,
  `[${lang('飞吻')}]`,
  `[${lang('鄙视')}]`,
  `[${lang('晕')}]`,
  `[${lang('大兵')}]`,
  `[${lang('可怜')}]`,
  `[${lang('强')}]`,
  `[${lang('弱')}]`,
  `[${lang('握手')}]`,
  `[${lang('胜利')}]`,
  `[${lang('抱拳')}]`,
  `[${lang('凋谢')}]`,
  `[${lang('米饭')}]`,
  `[${lang('蛋糕')}]`,
  `[${lang('西瓜')}]`,
  `[${lang('啤酒')}]`,
  `[${lang('瓢虫')}]`,
  `[${lang('勾引')}]`,
  `[${lang('OK')}]`,
  `[${lang('爱你')}]`,
  `[${lang('咖啡')}]`,
  `[${lang('月亮')}]`,
  `[${lang('刀')}]`,
  `[${lang('发抖')}]`,
  `[${lang('差劲')}]`,
  `[${lang('拳头')}]`,
  `[${lang('心碎了')}]`,
  `[${lang('太阳')}]`,
  `[${lang('礼物')}]`,
  `[${lang('皮球')}]`,
  `[${lang('骷髅')}]`,
  `[${lang('挥手')}]`,
  `[${lang('闪电')}]`,
  `[${lang('饥饿')}]`,
  `[${lang('咒骂')}]`,
  `[${lang('折磨')}]`,
  `[${lang('抠鼻')}]`,
  `[${lang('鼓掌')}]`,
  `[${lang('糗大了')}]`,
  `[${lang('左哼哼')}]`,
  `[${lang('打哈欠')}]`,
  `[${lang('快哭了')}]`,
  `[${lang('吓')}]`,
  `[${lang('篮球')}]`,
  `[${lang('乒乓')}]`,
  `[${lang('NO')}]`,
  `[${lang('跳跳')}]`,
  `[${lang('怄火')}]`,
  `[${lang('转圈')}]`,
  `[${lang('磕头')}]`,
  `[${lang('回头')}]`,
  `[${lang('跳绳')}]`,
  `[${lang('激动')}]`,
  `[${lang('街舞')}]`,
  `[${lang('献吻')}]`,
  `[${lang('左太极')}]`,
  `[${lang('右太极')}]`,
  `[${lang('闭嘴')}]`,
  `[${lang('猫咪')}]`,
  `[${lang('红双喜')}]`,
  `[${lang('鞭炮')}]`,
  `[${lang('红灯笼')}]`,
  `[${lang('麻将')}]`,
  `[${lang('麦克风')}]`,
  `[${lang('礼品袋')}]`,
  `[${lang('信封')}]`,
  `[${lang('象棋')}]`,
  `[${lang('彩带')}]`,
  `[${lang('蜡烛')}]`,
  `[${lang('爆筋')}]`,
  `[${lang('棒棒糖')}]`,
  `[${lang('奶瓶')}]`,
  `[${lang('面条')}]`,
  `[${lang('香蕉')}]`,
  `[${lang('飞机')}]`,
  `[${lang('左车头')}]`,
  `[${lang('车厢')}]`,
  `[${lang('右车头')}]`,
  `[${lang('多云')}]`,
  `[${lang('下雨')}]`,
  `[${lang('钞票')}]`,
  `[${lang('熊猫')}]`,
  `[${lang('灯泡')}]`,
  `[${lang('风车')}]`,
  `[${lang('闹钟')}]`,
  `[${lang('雨伞')}]`,
  `[${lang('彩球')}]`,
  `[${lang('钻戒')}]`,
  `[${lang('沙发')}]`,
  `[${lang('纸巾')}]`,
  `[${lang('手枪')}]`,
  `[${lang('青蛙')}]`,
]
