export const mapData = {
  loginName: 'loginNameisVisible',
  loginPwd: 'loginPwdisVisible',
  reLoginPwd: 'reLoginPwdisVisible',
  mobile: 'mobileisVisible',
  addressis: 'addressisVisible',
  emailis: 'emailisVisible',
  qq: 'qqisVisible',
  realName: 'realNameisVisible',
  mobileCaptchareg: 'mobileCaptcharegisVisible',
  weChat: 'weChatisVisible',
  whatsapp: 'whatsappisVisible',
  telegram: 'telegramisVisible',
  captchareg: 'captcharegisVisible',
}
